max_acceleration = 4.0
max_deceleration = 3.0
crossing_time = 8000
pelican_wait_time = 5000
pelican_go_time = 5000
road_length = 400.0
zebra_crossings = [80]
pelican_crossings = [300]
max_speed = 13.41

[simulation]
run_time = 600_000
num_pedestrians = 500
num_vehicles = 500
pedestrian_arrival_rate = 5
vehicle_arrival_rate = 5
