road_length = 500
zebra_crossings = [180, 440]
# zebra_crossings = [80, 200, 340]
pelican_crossings = []
# zebra_crossings = [80, 200]
# pelican_crossings = [340]
max_acceleration = 4.0
max_deceleration = 3.0
crossing_time = 8000
pelican_wait_time = 5000
pelican_go_time = 5000
max_speed = 13.41

[simulation]
run_time = 3600_000
# run_time = 1200_000
num_pedestrians = 500
num_vehicles = 500
# Functions:
# pedestrian_arrival_rate = 0.05
# vehicle_arrival_rate = 0.1
# pedestrian_arrival_rate = 0.3
# vehicle_arrival_rate = 0.3
# pedestrian_arrival_rate = 0.2
# vehicle_arrival_rate = 0.4
# pedestrian_arrival_rate = 0.2

# vehicle_arrival_rate = 0.1
# pedestrian_arrival_rate = 0.1

vehicle_arrival_rate = 0.2
# pedestrian_arrival_rate = 0.15
pedestrian_arrival_rate = 0.05

# vehicle_arrival_rate = 0.4
# pedestrian_arrival_rate = 0.4
# vehicle_arrival_rate = 0.5
# pedestrian_arrival_rate = 0.5
# vehicle_arrival_rate = 0.6
# pedestrian_arrival_rate = 0.6
