[simulation]
run_time = 600_000
num_pedestrians = 500
num_vehicles = 500
pedestrian_arrival_rate = 5
vehicle_arrival_rate = 5

road_length = 400 // Make longer for steady state
zebra_crossings = [80]
// zebra_crossings = [80, 200]
pelican_crossings = [340]


// Specify all the information for the struct otherwise will fail
[[crossings]]
type = "Zebra"
